export const paths = {
  UserDashboard: '/',
  UserQuest: '/user-quest',
  DailyReports: '/daily-reports',
  WeeklyReports: '/weekly-reports',
  EndOfDayReports: '/end-of-day-reports',
  LeaderBoard: '/leaderboard',
  login: '/login',
  register: '/register', 
  forgotpassword: '/forgotpassword',
  verification : '/verification',
  MenteesOverview: '/MenteesOverview',
  UserProfile: '/user-profile',
  AdminInvite: '/admin-invite',
  AdminBacklog: '/Admin-backlog',
  LearningRoadmap: '/learning-roadmap',
  AdminPosition: '/admin-position',
  MenteesQuests: '/MenteesQuests',
  notFound: '*',
} as const;
